from machine import Pin, PWM
import time
buzzer = PWM(Pin(0))
def buzzer_on(freq):
    buzzer.freq(freq)
    buzzer.duty_u16(32768)
def buzzer_off():
    buzzer.duty_u16(0)
def buzz(freq, buzz_time):
    buzzer_on(freq)
    time.sleep(buzz_time)
    buzzer_off()
def note0():
    buzz(400, 0.1)
def note1():
    buzz(450, 0.1)
def note2():
    buzz(500, 0.1)
def note3():
    buzz(550, 0.1)
def note4():
    buzz(600, 0.1)
def note5():
    buzz(650, 0.1)
def note6():
    buzz(700, 0.1)
def note7():
    buzz(750, 0.1)
def note8():
    buzz(800, 0.1)
def note9():
    buzz(850, 0.1)
def noteskip():
    time.sleep(0.1)
def beat0():
    note0()
    note1()
while True:
    note0()
    note1()
    noteskip()
    note2()
    note1()
    note2()
    note4()
    note6()
    note8()
    noteskip()
    note6()
    note5()
    note4()
    note5()
    note6()
    noteskip()
    note9()
    note8()
    note9()
    noteskip()
    note7()
    note6()
    note7()
    noteskip()
    note5()
    note4()
    note5()
    noteskip()
    note3()
    note2()
    note3()
    noteskip()
    note1()
    note0()
    note1()
    noteskip()
    noteskip()
    note2()
    note4()
    note6()
    note8()
    note0()
    note1()
    note2()
    noteskip()
    note1()
    note2()
    note3()
    note4()
    note3()
    note1()
    note3()
    noteskip()
    note3()
    note5()
    note3()
    note2()
    note4()
    note5()
    note7()
    note6()
    note6()
    noteskip()
    noteskip()
    note0()
    note0()
    noteskip()
    note2()
    note4()
    noteskip()
    note1()
    note3()
    note5()
    note7()
    noteskip()
    note8()
    note6()
    note3()
    note0()
    break
